name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

env:
  RUST_BINARY_NAME: rust_webserver
  DEPLOY_PATH: /home/ec2-user/rust_webserver

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Rust toolchain
      run: |
        rustup default nightly
        rustup update

    - name: Build Rust application
      run: cargo build --release

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # 기존 서버 종료
        ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@3.81.80.6 'pkill ${{ env.RUST_BINARY_NAME }} || true'
        
        # 바이너리 전송
        scp -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null target/release/${{ env.RUST_BINARY_NAME }} ec2-user@3.81.80.6:${{ env.DEPLOY_PATH }}
        
        # 서버 다시 시작
        ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@3.81.80.6 'nohup ${{ env.DEPLOY_PATH }}/${{ env.RUST_BINARY_NAME }} > /dev/null 2>&1 &'

        rm -f private_key.pem
